#!/bin/sh

# npx nx-cloud record -- npm run lint:styles
npx nx affected --target=lint --parallel=4 --configuration=development
npx nx affected --target=test --parallel=4 --configuration=development --ci
